/* Mochi Games Hub — optional presets, never pre-populated */
(function(){
const groups={
'Character & Gacha':['Genshin Impact','Honkai: Star Rail','Zenless Zone Zero','Wuthering Waves','Honkai Impact 3rd','Arknights','Arknights: Endfield','Fate/Grand Order','Blue Archive','Goddess of Victory: NIKKE',"Girls' Frontline","Girls' Frontline 2: Exilium",'Reverse: 1999','Love and Deepspace','Infinity Nikki','Punishing: Gray Raven','Azur Lane','Epic Seven','Guardian Tales','Path to Nowhere','Limbus Company','Brown Dust 2','AFK Journey','AFK Arena','Eversoul','Tower of Fantasy','Aether Gazer','Granblue Fantasy','Fire Emblem Heroes','Pokémon Masters EX','Pokémon TCG Pocket','Persona 5: The Phantom X','CookieRun: Kingdom','Dislyte','Summoners War','Sword of Convallaria','Another Eden','Last Cloudia','Octopath Traveler: Champions of the Continent','Dragon Ball Legends','Dragon Ball Z Dokkan Battle','One Piece Treasure Cruise','The Seven Deadly Sins: Grand Cross','Bleach: Brave Souls','Yu-Gi-Oh! Master Duel'],
'Life, Cozy & Roster':['Tomodachi Life: Living the Dream','Tomodachi Life','Animal Crossing: New Horizons','Disney Dreamlight Valley','Stardew Valley','The Sims 4','The Sims 3','Fields of Mistria','Coral Island','Palia','Story of Seasons','Harvest Moon','Rune Factory','My Time at Sandrock','My Time at Portia','Cozy Grove','Hello Kitty Island Adventure','Disney Magical World','Miitopia','Fantasy Life','Pokémon Pokopia','Ooblets','Dinkum','Spiritfarer'],
'Creatures & Pokédex':['Pokémon Scarlet & Violet','Pokémon Legends: Z-A','Pokémon Legends: Arceus','Pokémon Sword & Shield','Pokémon Brilliant Diamond & Shining Pearl',"Pokémon Let's Go Pikachu/Eevee",'Pokémon HOME','Pokémon GO','Pokémon TCG Live','Palworld','Digimon Story: Cyber Sleuth','Digimon Survive','Monster Hunter Stories','Monster Hunter Stories 2','Temtem'],
'RPG, Party & Completion':['Persona 3 Reload','Persona 4 Golden','Persona 5 Royal','Metaphor: ReFantazio','Final Fantasy VII Remake','Final Fantasy VII Rebirth','Final Fantasy XIV','Final Fantasy XVI','Xenoblade Chronicles','Xenoblade Chronicles 2','Xenoblade Chronicles 3','Fire Emblem: Three Houses','Fire Emblem Engage','Dragon Quest XI','Octopath Traveler','Octopath Traveler II','NieR: Automata','Kingdom Hearts','Baldur’s Gate 3','Elden Ring','The Legend of Zelda: Tears of the Kingdom','The Legend of Zelda: Breath of the Wild','Monster Hunter Wilds','Monster Hunter Rise','Monster Hunter World'],
'Competitive, Cards & Live Service':['Marvel Rivals','Overwatch 2','Valorant','League of Legends','Teamfight Tactics','Fortnite','Apex Legends','Hearthstone','Magic: The Gathering Arena','Marvel Snap','Pokémon UNITE','Splatoon 3','Super Smash Bros. Ultimate']};
const presets=[];Object.entries(groups).forEach(([category,names])=>names.forEach(name=>presets.push({name,category})));
function slug(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function typeFor(name){if(name==='Genshin Impact')return'genshin';if(name==='Tomodachi Life: Living the Dream')return'tomodachi-living-the-dream';if(/pokémon|palworld|digimon|temtem/i.test(name))return'creature';if(/animal crossing|stardew|sims|dreamlight|mii|tomodachi|cozy|palia|story of seasons|harvest moon/i.test(name))return'roster';if(/honkai|zenless|wuthering|arknights|fate|blue archive|nikke|azur|epic seven|granblue|fire emblem heroes/i.test(name))return'character';return'custom-game'}
const fieldSets={character:['Character','Rarity','Role','Level','Status'],creature:['Name','Species','Form','Level','Status'],roster:['Name','Type','Personality','Status'],'custom-game':['Name','Category','Status']};
function fieldsFor(name){const t=typeFor(name);if(t==='genshin')return['Element','Rarity','Weapon','Role','Nation','Constellation','Level'];if(t==='tomodachi-living-the-dream')return['Source Character','Source Series / Anime / Game','Island Personality','Canon Height (cm)'];return fieldSets[t]||fieldSets['custom-game']}
function templateFor(name){if(name==='Genshin Impact')return'genshin';if(name==='Tomodachi Life: Living the Dream')return'tomodachi';return'custom'}
function emojiFor(type){return type==='genshin'?'✨':type==='tomodachi-living-the-dream'?'🏝️':type==='creature'?'🐾':type==='roster'?'🏡':type==='character'?'⭐':'🎮'}
function gameCollections(){return state.collections.filter(c=>c.isGame||c.template==='genshin'||c.template==='tomodachi')}
function renderGameCard(c){return `<button class="game-library-card" data-game-collection="${c.id}"><span class="game-library-icon">${esc(c.emoji||'🎮')}</span><span><b>${esc(c.gamePreset||c.name)}</b><small>${itemsForCollection(c.id).length} tracked entr${itemsForCollection(c.id).length===1?'y':'ies'}</small></span><span>›</span></button>`}
function renderGames(){const mine=gameCollections();return `<div class="games-page"><div class="page-title-row"><div><div class="eyebrow">GAME TRACKERS</div><h2 class="page-title">Games</h2></div><button class="soft-btn primary" id="addGameBtn">+ Add Game</button></div><section class="games-hero"><h2>Your game collections</h2><p>Track characters, rosters, creatures, unlockables, builds, or anything else you collect in a game. Game-specific tools only appear after you choose that game.</p></section>${mine.length?`<div class="game-library-list">${mine.map(renderGameCard).join('')}</div>`:`<div class="game-empty panel"><div class="game-empty-icon">🎮</div><h3>No games added yet</h3><p>Choose a game preset or create a custom game tracker. Mochi won’t add any characters or sample data for you.</p><button class="soft-btn primary" id="emptyAddGameBtn">Choose a game</button></div>`}</div>`}
function drawPresetPicker(){const root=$('#gamePresetResults'),q=String($('#gamePresetSearch')?.value||'').trim().toLowerCase();if(!root)return;root.innerHTML=Object.entries(groups).map(([cat,names])=>{const matches=names.filter(n=>!q||n.toLowerCase().includes(q)||cat.toLowerCase().includes(q));if(!matches.length)return'';return `<div class="game-category">${esc(cat)}</div><div class="game-preset-grid">${matches.map(n=>`<button class="game-preset" data-game-preset="${esc(n)}"><b>${esc(n)}</b><small>${esc(typeFor(n).replaceAll('-',' '))}</small></button>`).join('')}</div>`}).join('')||'<div class="game-empty"><p>No matching preset. You can still make a Custom Game.</p></div>';$$('[data-game-preset]',root).forEach(b=>b.onclick=()=>createGameCollection(b.dataset.gamePreset))}
function openGamePicker(){openModal(`${modalHead('🎮 Add Game')}<p class="validation-note">Choose a preset for useful starting fields, or create a completely custom tracker. Nothing is pre-added.</p><input id="gamePresetSearch" class="game-search" placeholder="Search 100+ games…"><button id="customGameBtn" class="soft-btn" style="width:100%;margin-bottom:10px">＋ Custom Game</button><div id="gamePresetResults"></div>`);$('#gamePresetSearch').oninput=drawPresetPicker;$('#customGameBtn').onclick=openCustomGameForm;drawPresetPicker()}
async function createGameCollection(name){if(gameCollections().some(c=>(c.gamePreset||c.name).toLowerCase()===String(name).toLowerCase()))return showToast(`${name} is already in your Games.`, 'error');const type=typeFor(name),rec={id:uid('col'),name,gamePreset:name,isGame:true,gameType:type,emoji:emojiFor(type),template:templateFor(name),color:COLORS[state.collections.length%COLORS.length],cover:'',description:`${name} game tracker`,parentId:'',setTotal:'',setMembers:[],customFieldLabels:fieldsFor(name),order:state.collections.length,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),archived:false};await storePut(STORES.collections,rec);await loadData();closeModal();state.route='games';render();showToast(`${name} added to Games ♡`,'success')}
function openCustomGameForm(){openModal(`${modalHead('🎮 Custom Game')}<form id="customGameForm" class="form-grid"><div class="field"><label>Game name *</label><input name="name" maxlength="80" required placeholder="e.g. My favorite game"></div><div class="field"><label>Starting fields</label><input name="fields" placeholder="Name, Type, Level, Status"></div><div class="field"><label>Icon</label><input name="emoji" maxlength="4" value="🎮"></div><div class="form-actions"><button class="soft-btn" type="button" data-close-modal>Cancel</button><button class="soft-btn primary">Create game</button></div></form>`);$('#customGameForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),name=String(fd.get('name')||'').trim();if(!name)return;if(gameCollections().some(c=>c.name.toLowerCase()===name.toLowerCase()))return showToast('That game is already in your Games.','error');const fields=String(fd.get('fields')||'').split(',').map(x=>x.trim()).filter(Boolean);const rec={id:uid('col'),name,gamePreset:'',isGame:true,gameType:'custom-game',emoji:String(fd.get('emoji')||'🎮').trim()||'🎮',template:'custom',color:COLORS[state.collections.length%COLORS.length],cover:'',description:'Custom game tracker',parentId:'',setTotal:'',setMembers:[],customFieldLabels:fields.length?fields:[...fieldSets['custom-game']],order:state.collections.length,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),archived:false};await storePut(STORES.collections,rec);await loadData();closeModal();state.route='games';render();showToast(`${name} added to Games ♡`,'success')}}
const baseRender=render;render=function(){if(state.route!=='games')return baseRender();updateGreeting();$('#mainContent').innerHTML=renderGames();$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route==='games'));bindDynamicEvents();$('#addGameBtn')?.addEventListener('click',openGamePicker);$('#emptyAddGameBtn')?.addEventListener('click',openGamePicker);$$('[data-game-collection]').forEach(b=>b.onclick=()=>setRoute('collection',{collectionId:b.dataset.gameCollection}))};
const baseCollections=renderCollections;renderCollections=function(){const all=state.collections;state.collections=all.filter(c=>!c.isGame&&c.template!=='genshin'&&c.template!=='tomodachi');try{return baseCollections()}finally{state.collections=all}};
window.MochiGames={groups,presets,slug,typeFor,fieldsFor,getPreset:name=>presets.find(p=>p.name===name),makeGame:name=>({name:name||'Custom Game',gameType:typeFor(name||''),fields:fieldsFor(name||''),customizable:true})};
})();