/* Mochi Games Hub — optional presets, never pre-populated */
(function(){
const groups={
'Character & Gacha':['Genshin Impact','Honkai: Star Rail','Zenless Zone Zero','Wuthering Waves','Honkai Impact 3rd','Arknights','Arknights: Endfield','Fate/Grand Order','Blue Archive','Goddess of Victory: NIKKE',"Girls' Frontline","Girls' Frontline 2: Exilium",'Reverse: 1999','Love and Deepspace','Infinity Nikki','Punishing: Gray Raven','Azur Lane','Epic Seven','Guardian Tales','Path to Nowhere','Limbus Company','Brown Dust 2','AFK Journey','AFK Arena','Eversoul','Tower of Fantasy','Aether Gazer','Granblue Fantasy','Fire Emblem Heroes','Pokémon Masters EX','Pokémon TCG Pocket','Persona 5: The Phantom X','CookieRun: Kingdom','Dislyte','Summoners War','Sword of Convallaria','Another Eden','Last Cloudia','Octopath Traveler: Champions of the Continent','Dragon Ball Legends','Dragon Ball Z Dokkan Battle','One Piece Treasure Cruise','The Seven Deadly Sins: Grand Cross','Bleach: Brave Souls','Yu-Gi-Oh! Master Duel'],
'Life, Cozy & Roster':['Tomodachi Life: Living the Dream','Tomodachi Life','Animal Crossing: New Horizons','Disney Dreamlight Valley','Stardew Valley','The Sims 4','The Sims 3','Fields of Mistria','Coral Island','Palia','Story of Seasons','Harvest Moon','Rune Factory','My Time at Sandrock','My Time at Portia','Cozy Grove','Hello Kitty Island Adventure','Disney Magical World','Miitopia','Fantasy Life','Pokémon Pokopia','Ooblets','Dinkum','Spiritfarer'],
'Creatures & Pokédex':['Pokémon Scarlet & Violet','Pokémon Legends: Z-A','Pokémon Legends: Arceus','Pokémon Sword & Shield','Pokémon Brilliant Diamond & Shining Pearl',"Pokémon Let's Go Pikachu/Eevee",'Pokémon HOME','Pokémon GO','Pokémon TCG Live','Palworld','Digimon Story: Cyber Sleuth','Digimon Survive','Monster Hunter Stories','Monster Hunter Stories 2','Temtem'],
'RPG, Party & Completion':['Persona 3 Reload','Persona 4 Golden','Persona 5 Royal','Metaphor: ReFantazio','Final Fantasy VII Remake','Final Fantasy VII Rebirth','Final Fantasy XIV','Final Fantasy XVI','Xenoblade Chronicles','Xenoblade Chronicles 2','Xenoblade Chronicles 3','Fire Emblem: Three Houses','Fire Emblem Engage','Dragon Quest XI','Octopath Traveler','Octopath Traveler II','NieR: Automata','Kingdom Hearts','Baldur’s Gate 3','Elden Ring','The Legend of Zelda: Tears of the Kingdom','The Legend of Zelda: Breath of the Wild','Monster Hunter Wilds','Monster Hunter Rise','Monster Hunter World'],
'Competitive, Cards & Live Service':['Marvel Rivals','Overwatch 2','Valorant','League of Legends','Teamfight Tactics','Fortnite','Apex Legends','Hearthstone','Magic: The Gathering Arena','Marvel Snap','Pokémon UNITE','Splatoon 3','Super Smash Bros. Ultimate']};
const presets=[];Object.entries(groups).forEach(([category,names])=>names.forEach(name=>presets.push({name,category})));
function slug(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function typeFor(name){if(name==='Genshin Impact')return'genshin';if(name==='Tomodachi Life: Living the Dream')return'tomodachi-living-the-dream';if(/pokémon|palworld|digimon|temtem/i.test(name))return'creature';if(/animal crossing|stardew|sims|dreamlight|mii|tomodachi|cozy|palia|story of seasons|harvest moon/i.test(name))return'roster';if(/honkai|zenless|wuthering|arknights|fate|blue archive|nikke|gacha|azur|epic seven|granblue|fire emblem heroes/i.test(name))return'character';return'custom-game'}
const fieldSets={character:['Character','Rarity','Role','Level','Status'],creature:['Name','Species','Form','Level','Status'],roster:['Name','Type','Personality','Status'], 'custom-game':['Name','Category','Status']};
window.MochiGames={groups,presets,slug,typeFor,getPreset:name=>presets.find(p=>p.name===name),fieldsFor:name=>{const t=typeFor(name);if(t==='genshin')return['Element','Rarity','Weapon','Role','Nation','Constellation','Level'];if(t==='tomodachi-living-the-dream')return['Source Character','Series','Personality','Canon Height'];return fieldSets[t]||fieldSets['custom-game'];},makeGame:name=>({id:'game-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),name:name||'Custom Game',preset:name||null,gameType:typeFor(name||''),fields:[...((name&&window.MochiGames.fieldsFor(name))||fieldSets['custom-game'])],customizable:true,createdAt:new Date().toISOString()})};
/* Presets are suggestions only. Nothing is added to user data until explicitly selected. */
})();